spring:
  application:
    name: user-service-api
    version: 1.0.0

  datasource:
    url: jdbc:postgresql://user-service-db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  cache:
    type: redis
    redis:
      key-prefix: "user-service-api::"
      time-to-live: 10m
      use-key-prefix: true
      cache-null-values: false

  data:
    redis:
      host: cache
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      fail-fast: false
    properties:
      spring.json.add.type.headers: false

app:
  kafka:
    topic:
      orders: ${APP_KAFKA_TOPIC_ORDERS:orders.create.v1}