version: "3.9"
services:
  user-service-db:
    image: postgres:17
    container_name: user-service-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  cache:
    image: redis:7.0.0-alpine
    container_name: cache
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"


  user-service-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service-api
    ports:
      - "8080:8080"
    depends_on:
      - user-service-db
      - cache